tunnel: 0f0ed3ef-95f5-45bd-9598-11bb9dcac979
credentials-file: /home/cloudflared/credentials.json
origincert: /home/cloudflared/cert.pem

ingress:
  - hostname: api.booppa.io
    service: http://booppa-app.booppa.local:8000
  - hostname: cms.booppa.io
    service: http://booppa-cms.booppa.local:8001
  - service: http_status:404