tunnel: 0f0ed3ef-95f5-45bd-9598-11bb9dcac979
credentials-file: /home/cloudflared/credentials.json
origincert: /home/cloudflared/cert.pem

ingress:
  - hostname: api.booppa.io
    service: http://127.0.0.1:8000
  - hostname: cms.booppa.io
    service: http://127.0.0.1:8001
  - hostname: admin.booppa.io
    service: http://127.0.0.1:8001
  - service: http_status:404